name: deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… ì²´í¬ì•„ì›ƒ source code.
        uses: actions/checkout@v3

      - name: âš™ï¸ Node.js ì„¤ì •
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Node.js 20 ë²„ì „ì„ ì‚¬ìš©
          cache: 'yarn'  # Yarn ìºì‹œ ì‚¬ìš© í™œì„±í™”
          cache-dependency-path: 'Server/withus-express/yarn.lock'

      - name: âš™ï¸ í™˜ê²½ë³€ìˆ˜ë¥¼ ì„¤ì •í•©ë‹ˆë‹¤.
        working-directory: Server/withus-express
        run: |
          pwd
          touch .env
          echo DATABASE_URL=${{ secrets.DB_URL }} >> .env
          cat .env

      - name: âœ¨ íŒ¨í‚¤ì§€ ì„¤ì¹˜
        run: yarn
        working-directory: Server/withus-express

      - name: âœ¨ ë¹Œë“œ ê³¼ì •ì„ ì‹œì‘
        run: yarn run build
        working-directory: Server/withus-express

      - name: ğŸ“¦ ë¹Œë“œí•œ ì½”ë“œë¥¼ ì••ì¶•
        run: zip -r withus.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

      - name: ğŸŒ AWSì— ì ‘ì†
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ğŸ¦– S3ì— ì••ì¶•ëœ ì„œë²„ ì½”ë“œë¥¼ ì—…ë¡œë“œ
        run: aws s3 cp --region ap-northeast-2 ./withus.zip s3://withus-build/deploy/

      - name: ğŸš€ AWS codeDeployë¡œ ë°°í¬ë¥¼ ì‹œì‘
        run: aws deploy create-deployment
          --application-name withus-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name dev
          --s3-location bucket=withus-build,bundleType=zip,key=deploy/withus.zip
      # - name: ğŸš€ ë°°í¬
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/Server/Server/withus-express
      #       git pull origin main
      #       npm install
      #       pm2 restart all
